/**
 ******************************************************************************
 * @addtogroup UAVObjects OpenPilot UAVObjects
 * @{ 
 * @addtogroup $(NAME) $(NAME)
 * @brief $(DESCRIPTION)
 *
 * Autogenerated files and functions for $(NAME) Object
 * @{ 
 *
 * @file       $(NAMELC).c
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Implementation of the $(NAME) object. This file has been 
 *             automatically generated by the UAVObjectGenerator.
 * 
 * @note       Object definition file: $(XMLFILE). 
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#include "openpilot.h"
#include "$(NAMELC).h"
#include "$(NAMELC)mavlinkadapter.h"

int16_t get$(NAME)ParamIndexByName(const char* name)
{
	for (int i = 0; i < $(LOCALFIELDCOUNT); ++i)
	{
		bool match = true;
		const char* storage_name = get$(NAME)ParamNameByIndex(i);
		for (uint8_t j = 0; j < ONBOARD_PARAM_NAME_LENGTH; ++j)
		{
			// Compare
			if (storage_name[j] != name[j])
			{
				match = false;
			}

			// End matching if null termination is reached
			if (storage_name[j] == '\0')
			{
				break;
			}
		}
		if (match) return i;
	}
	return -1;
}

const char* get$(NAME)ParamNameByIndex(uint16_t index)
{
	switch (index)
	{
//		case 0:
//			return "fixedwing_roll1";
//		case 1:
//			return "fixedwing_roll2";
$(GETPARAMNAMEBYINDEXLINES)
	}
	return '\0';
}

uint8_t get$(NAME)ParamByIndex(uint16_t index, mavlink_param_union_t* param)
{
	$(NAME)Data settings;
	$(NAME)Get(&settings);
	switch ($(GLOBALTOTALFIELDOFFSET) + index)
	{
$(GETPARAMBYINDEXLINES)
//		case 0:
//		{
//			param->param_uint32 = settings.FixedWingRoll1;
//			param->type = MAVLINK_TYPE_UINT32_T;
//		}
//			break;
//		case 1:
//		{
//			param->param_uint32 = settings.FixedWingRoll2;
//			param->type = MAVLINK_TYPE_UINT32_T;
//		}
//			break;
		default:
		{
			return MAVLINK_RET_VAL_PARAM_NAME_DOES_NOT_EXIST;
		}
			break;
	}
	// Not returned in default case, return true
	return MAVLINK_RET_VAL_PARAM_SUCCESS;
}

uint8_t set$(NAME)ParamByIndex(uint16_t index, const mavlink_param_union_t* param)
{
	$(NAME)Data settings;
	$(NAME)Get(&settings);
	switch (index)
	{
$(SETPARAMBYINDEXLINES)
//		case 0:
//		{
//			if (param->type == MAVLINK_TYPE_UINT32_T)
//			{
//				settings.FixedWingRoll1 = param->param_uint32;
//			}
//			else
//			{
//				return MAVLINK_RET_VAL_PARAM_TYPE_MISMATCH;
//			}
//		}
//			break;
//		case 1:
//		{
//			if (param->type == MAVLINK_TYPE_UINT32_T)
//			{
//				settings.FixedWingRoll2 = param->param_uint32;
//			}
//			else
//			{
//				return MAVLINK_RET_VAL_PARAM_TYPE_MISMATCH;
//			}
//		}
//			break;
		default:
		{
			return MAVLINK_RET_VAL_PARAM_NAME_DOES_NOT_EXIST;
		}
			break;
	}

	// Not returned in default case, try to write (ok == 0) and return result of
	// write operation
	if ($(NAME)Set(&settings) == 0)
	{
		return MAVLINK_RET_VAL_PARAM_SUCCESS;
	}
	else
	{
		return MAVLINK_RET_VAL_PARAM_WRITE_ERROR;
	}
}

/**
 * @}
 */

