/**
 ******************************************************************************
 * @addtogroup UAVObjects OpenPilot UAVObjects
 * @{ 
 * @addtogroup $(NAME)MAVLinkAdapter $(NAME)MAVLinkAdapter
 * @brief $(DESCRIPTION)
 *
 * Autogenerated files and functions for $(NAME)MAVLinkAdapter Object
 
 * @{ 
 *
 * @file       $(NAMELC).h
 * @author     The OpenPilot Team, http://www.openpilot.org Copyright (C) 2010.
 * @brief      Implementation of the $(NAME) object. This file has been 
 *             automatically generated by the UAVObjectGenerator.
 * 
 * @note       Object definition file: $(XMLFILE). 
 *             This is an automatically generated file.
 *             DO NOT modify manually.
 *
 * @see        The GNU Public License (GPL) Version 3
 *
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 */

#ifndef $(NAMEUC)MAVLINKADAPTER_H
#define $(NAMEUC)MAVLINKADAPTER_H

int16_t get$(NAME)ParamIndexByName(const char* name);
const char* get$(NAME)ParamNameByIndex(uint16_t index);
uint8_t get$(NAME)ParamByIndex(uint16_t index, mavlink_param_union_t* param);
uint8_t set$(NAME)ParamByIndex(uint16_t index, const mavlink_param_union_t* param);

#endif // $(NAMEUC)MAVLINKADAPTER_H

/**
 * @}
 * @}
 */
